# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cabe8f63f6c678dc20c2db5ecdfaf039df5e6e05ae2ef6f5983ab59cec5cda66154566c4f677b54ab99dcf4bda485fbf54da899b583f7dd737ded177fc29bde

test:
  secret_key_base: d76025c89dca72f56b9fe87c72efc020602a758e524b7cf1bfadd58ead90c5f36cf2ea14977ec8bbbc4839ad947342e03fcca2be19c42208fb596ee694512d1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 1332911960068605
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
